GroupNameFormNameページをAtomic Designに則ったコンポーネント構造にした
gKokasai/panel.kokasai.com pull request #122
Opened 2021-05-21 05:10 UTC by cheichey

- GroupNameFormNameのHeaderはUserContextのformListから参照するためWithHeaderListのpropsのtitleをundefined許容した。

2021-05-21 05:26 UTC, sya-ri requested changes

2021-05-21 05:26 UTC, sya-ri commented on src/components/organisms/group/GroupNameFormContent.tsx
> +                        );
string, check 単位でコンポーネントを切り分けておいた方が今後の追加が簡単になると思います。type名とオブジェクトでJSX.Elementを返す処理を外部で実装しましょう

2021-05-21 06:06 UTC, cheichey commented on src/components/organisms/group/GroupNameFormContent.tsx
> +                        );
外部というのはmoleculesで行うのでいいのでしょうか

2021-05-21 06:21 UTC, sya-ri commented on src/components/organisms/group/GroupNameFormContent.tsx
> +                        );
問題ないと思います

2021-05-26 01:13 UTC, cheichey commented on src/components/molecules/group/FormElement.tsx
> +                      {formDataValueType[1].element[id as keyof string]}
個々の部分がうまく動かないのですが見てもらってもいいですか？

2021-05-26 01:29 UTC, sya-ri commented on src/components/molecules/group/FormElement.tsx
> +                      {formDataValueType[1].element[id as keyof string]}
```tsx
const keys = Object.keys(formDataValueType[1]);
```
element の keys を取得していません

2021-05-26 01:36 UTC, cheichey commented
この実装でいいのかわからないのですが、一応前のコードと同じように動くようにはなりました。
よろしくお願いします。

2021-05-26 01:50 UTC, sya-ri requested changes

2021-05-26 01:50 UTC, sya-ri commented on src/components/molecules/group/FormElement.tsx
> +          if (formDataValueType[0] === 'check') {
ifを連続させて、このような書き方をしてしまうとコードが長くなってしまいます。別の場所に書くようにしてください

2021-05-26 03:59 UTC, cheichey commented on src/components/molecules/group/FormElement.tsx
> +            )
三項演算子で書き換えました

2021-05-26 05:27 UTC, sya-ri commented on src/components/molecules/group/FormElement.tsx
> +            )
面倒なので自分で実装します

2021-05-26 05:27 UTC, sya-ri approved these changes

2021-05-26 05:28 UTC, merged