追加されたAPIの機能に対応した関数を追加した
gKokasai/panel.kokasai.com pull request #59
Opened 2021-05-10 06:52 UTC by axelaspor2

2021-05-10 07:06 UTC, cheichey commented
元ブランチを間違えたので#58がマージされてからforce pushしますのでいったん保留でお願いします

2021-05-10 09:39 UTC, cheichey commented
@sya-ri お願いします

2021-05-10 09:40 UTC, sya-ri commented
https://github.com/gKokasai/api.kokasai.com/commit/f0e7be58be3ee523403934fa7ad44727ffc9a162
https://github.com/gKokasai/api.kokasai.com/commit/9370ab281a5d9cf711bf39f71f7972b9ab7bbc80

申し訳ないのですが、こちらの変更も対応してください

2021-05-10 09:46 UTC, sya-ri requested changes
上記の内容に対応したらマージします

2021-05-10 10:21 UTC, cheichey commented
変更しました

2021-05-10 21:34 UTC, sya-ri requested changes

2021-05-10 21:34 UTC, sya-ri commented on src/api/api.ts
> -export const getDocument = (documentName: string): Promise<AxiosResponse> => axios.get(`${URL}/document/${documentName}`);
documentName を指定しない getDocument を追加しただけなので削除する必要はありません

2021-05-10 21:34 UTC, sya-ri commented on src/api/api.ts
> +export const getDocumentList = (): Promise<AxiosResponse<{document: string[]}>> => axios.get(`${URL}/document`);
関数のオーバーライドが可能なのであれば、getDocument() でいいと思います

2021-05-10 21:34 UTC, sya-ri commented on src/api/api.ts
> +export const postGroupForm = (groupName: string, formName: string, values: {[id: number]: FormSaveType}): Promise<AxiosResponse<string>> => axios.post(`${URL}/group/form/submit/${groupName}/${formNam
postGroupFormSubmit にしてください。今後、postGroupFormResponse 等が追加される可能性があります

2021-05-10 21:34 UTC, sya-ri commented on src/api/dataType.ts
> +      checkBoxId: string,
map<int, string> です

2021-05-11 00:06 UTC, sya-ri commented
> JavaScriptは関数のオーバーライドが不可能なので、getAllDocumentで対応しました

言葉を間違えました。オーバーロードです。オーバーロードは出来るようです。
https://qiita.com/suin/items/7d6837a0342b36891099

2021-05-11 00:10 UTC, cheichey commented on src/api/dataType.ts
> +      [checkBoxId: string]: string,
メソッドのオーバーロードはできても関数のオーバーロードはできないと思います

2021-05-11 00:32 UTC, merged