GroupNameFormNameのスタイルを改善
gKokasai/panel.kokasai.com pull request #92
Opened 2021-05-18 00:50 UTC by cheichey

2021-05-18 01:30 UTC, sya-ri requested changes
eslint に指摘されている内容を直してください

2021-05-18 02:56 UTC, cheichey commented
修正しました。お願いします

2021-05-18 06:01 UTC, sya-ri requested changes
各内容について返信してください

2021-05-18 06:01 UTC, sya-ri commented on src/api/dataType.ts
> +    {}
対象が短いので
```tsx
    {} // eslint-disable-line @typescript-eslint/ban-types
```
の方が良いと思います。

2021-05-18 06:01 UTC, sya-ri commented on src/components/pages/group/GroupNameFormName.tsx
> +import Checkbox from '@material-ui/core/Checkbox';
atoms に入れないんですか？

2021-05-18 06:01 UTC, sya-ri commented on tsconfig.json
> +    "suppressImplicitAnyIndexErrors": true,
なぜこのコンフィグを追加したのですか？

2021-05-18 06:05 UTC, cheichey commented on tsconfig.json
> +    "suppressImplicitAnyIndexErrors": true,
[参考記事](https://qiita.com/gonta/items/fb7b9e6d0f12060c27d6)
この記事で説明されてるようにkeyの型を指定したにもかかわらずエラーが出ているためです

2021-05-18 06:05 UTC, cheichey commented on src/components/pages/group/GroupNameFormName.tsx
> +import Checkbox from '@material-ui/core/Checkbox';
入れ忘れです

2021-05-18 06:05 UTC, cheichey commented on src/api/dataType.ts
> +    {}
分りました

2021-05-18 06:15 UTC, sya-ri commented on tsconfig.json
> +    "suppressImplicitAnyIndexErrors": true,
```tsx
{formDataValueType[1].element[id as keyof string]}
```
このように keyof を指定してあげればエラーになりませんでした

2021-05-19 05:32 UTC, sya-ri approved these changes

2021-05-19 05:32 UTC, merged